modLoader="javafml"
loaderVersion="[40,)"
license="GPL-3.0-or-later"

[[mods]]
  modId="atme"
  version="${file.jarVersion}"
  displayName="@Me"
  description='''
  Gay
  '''

  [[dependencies.atme]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
  [[dependencies.atme]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"